//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FileBX.rc
//
#define ID_HELP_UPLINKS                 3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_FAVORITES                   102
#define IDS_UNREG_MNU1                  102
#define IDS_UNREG_MNU2                  103
#define IDS_NOT_REGISTERED              104
#define IDS_REG_FEATURES                105
#define IDS_PROD_INFO                   106
#define IDR_HTML_HEADERDLG              107
#define IDR_MAINFRAME                   128
#define IDI_MAINFRAME_HICOLOR           129
#define IDR_TRAY_MENU                   131
#define IDI_TEXT                        140
#define IDI_SEPARATOR                   141
#define IDD_NEW_ITEM                    144
#define IDD_FILEBX                      145
#define IDD_SETTINGS                    146
#define IDC_FBX_HAND                    146
#define IDD_UPDATE_LINKS                148
#define IDB_BUTTONS                     153
#define IDD_KEY_SETTINGS                153
#define IDD_EXCEPTIONS                  155
#define IDD_OPTIONS                     156
#define IDD_HEADER                      160
#define IDD_ABOUTBOX1                   161
#define IDB_HYPER_LOGO                  165
#define IDB_MP_LOGO                     166
#define IDI_FAVORITES                   1000
#define IDI_RECENT                      1001
#define IDC_DBG_MSG                     1002
#define IDI_FOLDER                      1002
#define IDI_FILE                        1003
#define IDC_TREE1                       1004
#define IDS_PROG_FILES                  1004
#define IDS_DLL_FILES                   1005
#define IDS_ON_TOP                      1006
#define IDS_ROLL_UP                     1007
#define IDC_TEST                        1009
#define IDC_CHANGE_FOLDER               1010
#define IDC_CLOSE                       1011
#define IDC_ABOUT                       1012
#define ID_EDIT_FV                      1014
#define IDC_NEW_SHORTCUT                1015
#define IDC_NEW_SUBMENU                 1017
#define IDC_ADD_SEPARATOR               1018
#define IDC_DELETE                      1019
#define IDC_RENAME                      1020
#define IDC_EDIT_ITEM                   1021
#define IDC_ITEM_INFO                   1022
#define IDC_ENABLE_FBX                  1023
#define IDC_DELETE_ALL                  1024
#define IDC_MAX_RECENT                  1025
#define IDC_EXIT                        1026
#define IDC_FAV_FRAME                   1027
#define IDC_HELP_TEXT                   1028
#define IDC_ITEM_DESC                   1029
#define IDC_ITEM_TARGET                 1030
#define IDC_BROWSE_FOLDER               1031
#define IDC_BROWSE_FILE                 1032
#define IDC_ITEM_TYPE                   1033
#define IDC_EMAIL                       1034
#define IDC_HTTP                        1035
#define IDC_STATIC_RECENT               1036
#define IDC_STATIC_RECENT2              1037
#define IDC_HELP_FBX                    1038
#define IDC_HELP_ITPROP                 1039
#define IDC_TRAY_ICON                   1040
#define IDC_EXPLORER                    1041
#define IDC_FOLDERS_EXPL                1042
#define IDC_TAB1                        1043
#define IDC_RADIO1                      1054
#define IDC_RADIO2                      1055
#define IDC_RADIO3                      1056
#define IDC_SORT_COL2                   1057
#define IDC_SORT_COL3                   1058
#define IDC_SORT_COL4                   1059
#define IDC_DETAILED                    1064
#define IDC_RESIZE                      1065
#define IDC_RESIZE2                     1066
#define IDC_RESIZE3                     1067
#define IDC_HOTKEY_FAV                  1068
#define IDC_HOTKEY_REC                  1069
#define IDC_NUM_FAVORITES               1070
#define IDC_NUM_RECENT                  1071
#define IDC_ADDNUM_FAVORITES            1072
#define IDC_ADDNUM_RECENT               1073
#define IDC_MOVE_LEFT                   1102
#define IDC_RESIZE_WIDTH                1103
#define IDC_UPDATE_LINKS                1104
#define IDC_RESIZE_HEIGHT               1105
#define IDC_RECENT_PATH                 1106
#define IDC_MOVE_LEFTMAX                1107
#define IDC_RECENT_SORT                 1107
#define IDC_STATIC_PIXELS               1108
#define IDC_SYSMNU_TOPMOST              1108
#define IDC_STATIC_PIXELS2              1109
#define IDC_SYSMNU_ROLLUP               1109
#define IDC_STATIC_PIXELS3              1110
#define IDC_RECENT_FROMWIN              1110
#define IDC_STATIC_PIXELS4              1111
#define IDC_CFG_FOLDER                  1207
#define IDC_EXCEPTIONS                  1208
#define IDC_ADD_EXCEPT                  1209
#define IDC_DEL_EXCEPT                  1210
#define IDC_EXC_LIST                    1212
#define IDC_EX_RADIO1                   1213
#define IDC_EX_RADIO2                   1214
#define IDC_EX_RADIO3                   1215
#define IDC_EX_RADIO4                   1216
#define IDC_HELP_EXCEPT                 1217
#define IDC_VERSION                     1218
#define IDC_DISP_FAVFB                  1219
#define IDC_DISP_FAVEX                  1220
#define IDC_DISP_RECFB                  1221
#define IDC_DISP_RECEX                  1222
#define IDC_EX_FOLDERBTNS               1223
#define IDC_EX_HRESIZE                  1224
#define IDC_EX_VRESIZE                  1225
#define IDC_DISP_PUSHPIN                1226
#define IDC_EX_DONTHANDLE               1227
#define IDC_DISP_ROLLUP                 1227
#define IDC_EX_NOPIN                    1228
#define IDC_ROLLED_TOPMOST              1228
#define IDC_DETAILED_ASIZ               1229
#define IDC_EX_NOROLL                   1229
#define IDC_SORT_COL1                   1230
#define IDC_SORT_FRAME                  1232
#define IDC_SORT_ORD1                   1233
#define IDC_SORT_ORD2                   1234
#define IDC_CLICKSWITCH1                1235
#define IDC_CLICKSWITCH2                1236
#define IDC_CLICKSWITCH3                1237
#define IDC_TOGGLE_INFO                 1240
#define IDC_FILLRECENT                  1241
#define IDC_GNU_LICENSE                 1242
#define IDC_BUTTON1                     1243
#define IDC_CONTRIBUTORS                1243
#define IDR_DISABLED                    2000
#define IDC_DRAG_ITEM                   32766
#define ID_OPENWIN                      32772
#define ID_EXIT                         32773
#define IDS_ERR_MOVE                    32774
#define IDS_ERR_RENAME                  32775
#define ID_OPEN                         32776
#define IDS_STRING32776                 32776
#define IDP_OLE_INIT_FAILED             32777
#define IDS_MAINTAIN_FAV                32778
#define IDS_FOLDER_SHORTCUT             32779
#define IDS_BROKEN_SHORTCUT             32780
#define IDS_EXIT_PROMPT                 32781
#define IDS_FILE_SHORTCUT               32782
#define IDS_IS_SUBMENU                  32783
#define IDS_IS_TEXT                     32784
#define IDS_IS_SEPARATOR                32785
#define IDS_NEW_SUBMENU                 32786
#define IDS_SHORTCUT_FOLD               32787
#define IDS_SHORTCUT_FILE               32788
#define IDS_TEXT_ITEM                   32789
#define IDS_DELETE_ALL                  32790
#define IDS_DELETE_HINT                 32791
#define IDS_PRESS_HELP                  32792
#define IDS_TYPE_NEW_NAME               32793
#define IDS_MOVE_ITEM                   32794
#define IDS_CREATE_DROP                 32795
#define IDS_BETA_EXPIRED                32796
#define IDS_FOLDER_SELECT               32800
#define IDS_VIRUS                       32801
#define IDS_ERR_SAVELIC                 32802
#define IDS_LICENSE_OK                  32803
#define IDS_LIC_BAD                     32804
#define IDS_INVALID_FOLDER              32805
#define IDS_COPY_FAILED                 32806
#define IDS_CONF_NOBACKUP               32807
#define IDS_BK_FOLDER_SEL               32808
#define IDS_BACKUP_OK                   32809
#define IDS_UNLICENSED                  32810
#define IDS_READLIC_TITLE               32811
#define IDS_LIC_FILTER                  32812
#define IDS_ALL_FILES                   32813
#define IDS_LIC_INCORRECT               32814
#define IDS_DEL_LIC                     32815
#define IDS_DEL_LIC2                    32816
#define IDS_DELLIC_ERR                  32817
#define IDS_GETFBX_MNU1                 32818
#define IDS_GETFBX_MNU2                 32819
#define IDS_INFO                        32820
#define IDS_ADD                         32821
#define IDS_REMOVE                      32822
#define IDS_RECENT_FOLDERS              32823
#define IDS_FOLDER_SELECT2              32824
#define IDS_CFG_FOLDER_EMPTY            32825
#define IDS_CFG_FOLDER_NOT_EMPTY        32826

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        168
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1244
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
